---
title: "Modeling Assignment 1, Hendrik's benchmark"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setup

```{r}
# add your libraries
library(tidyverse)
library(caret)
library(rpart)
library(formatR)
library(moderndive)
library(class)
library(fastDummies)
library(tidytext)
library(ggalluvial)

# wine = read_rds("./pinot.rds") 
wine = read_rds("~/Desktop/MSDS/505-ML/resources/pinot.rds")

head(wine)
```


## Feature Engineering

```{r}
# create some cool features. Make sure you add comments so I know what you are trying to accomplish!

#make list of words from the wine's description
data(stop_words)

regex_ify<-function(x){
  x<-x[!is.na(x)]
  step1<-paste0("[ |^]",x,"[| |$]")
  step2<-paste0(step1,collapse="|")
  return(step2)
}

#full list of words, case insensitive and remove punctuation
all_description_words<-data.frame(stringr::str_split(wine$description," ",simplify=T),province=wine$province,id=wine$id) %>% 
  pivot_longer(c(-province,-id),values_to="word") %>% 
  mutate(word=tolower(word),
         word=gsub("[[:punct:]]","",word)
         ) %>% 
  filter(word!="")

#remove non-alpha words and remove stop words
all_description_words = all_description_words %>%
  filter(str_detect(string = word, pattern = "[a-z+]")) %>%  # get rid weird non alphas
  anti_join(stop_words)

#word summary by province
word_summary_province<-all_description_words %>% 
  group_by(province) %>% 
  summarise(
    total_words_in_prov=n(),
    unique_words_in_prov=n_distinct(word),
    total_wines_in_prov=n_distinct(id),
  )

#frequency analysis to identify words description of one province but not others
some_metrics<-all_description_words %>% 
  group_by(word,province) %>% 
  summarise(
    count=n(),
    wines=n_distinct(id)
  ) %>% 
  left_join(
    word_summary_province
  ) %>% 
  mutate(
    metric_1=count/total_words_in_prov, #frequency that word appears relative to all words in province
    metric_2=wines/total_wines_in_prov #frequency that wine with that word appear relative to all wines in province
  ) %>% 
  group_by(word) %>% 
  mutate(
    metric_3=metric_2/sum(metric_2), #relative frequency that word appears in province relative to other provinces
    metric_4=wines/sum(wines) #if you used this word to guess this wine's province how often would you be right
  )

not_these_words<-all_description_words %>% 
  group_by(word) %>% 
  filter(n()>1)
neg_words<-expand.grid(word=unique(not_these_words$word),province=unique(not_these_words$province)) %>% 
  anti_join(some_metrics)

#create features for model
ca_words<-some_metrics$word[some_metrics$metric_4>=1&some_metrics$province=="California"&some_metrics$wines>=1][1:2500]
or_words<-some_metrics$word[some_metrics$metric_4>=1&some_metrics$province=="Oregon"&some_metrics$wines>=1][1:2500]
ny_words<-some_metrics$word[some_metrics$metric_4>=1&some_metrics$province=="New_York"&some_metrics$wines>=1]
ma_words<-some_metrics$word[some_metrics$metric_4>=1&some_metrics$province=="Marlborough"&some_metrics$wines>=1]
cv_words<-some_metrics$word[some_metrics$metric_4>=1&some_metrics$province=="Casablanca_Valley"&some_metrics$wines>=1]
bu_words<-some_metrics$word[some_metrics$metric_4>=1&some_metrics$province=="Burgundy"&some_metrics$wines>=1]
ca_words2<-some_metrics$word[some_metrics$metric_4>=.8&some_metrics$metric_4<1&some_metrics$province=="California"&some_metrics$wines>=1]
or_words2<-some_metrics$word[some_metrics$metric_4>=.7&some_metrics$metric_4<1&some_metrics$province=="Oregon"&some_metrics$wines>=1]
ny_words2<-some_metrics$word[some_metrics$metric_4>=.3&some_metrics$metric_4<1&some_metrics$province=="New_York"&some_metrics$wines>=1]
ma_words2<-some_metrics$word[some_metrics$metric_4>=.3&some_metrics$metric_4<1&some_metrics$province=="Marlborough"&some_metrics$wines>=1]
cv_words2<-some_metrics$word[some_metrics$metric_4>=.3&some_metrics$metric_4<1&some_metrics$province=="Casablanca_Valley"&some_metrics$wines>=1]
bu_words2<-some_metrics$word[some_metrics$metric_4>=.7&some_metrics$metric_4<1&some_metrics$province=="Burgundy"&some_metrics$wines>=1]

not_these_words<-all_description_words %>% 
  group_by(word) %>% 
  filter(n()>1) %>% 
  filter(!word%in%c(ca_words,or_words,ny_words,ma_words,cv_words,bu_words))
neg_words<-expand.grid(word=unique(not_these_words$word),province=unique(not_these_words$province)) %>% 
  anti_join(some_metrics) %>% 
  left_join(
    not_these_words %>% 
      group_by(word) %>% 
      summarise(provs=n_distinct(province),count=n())) %>% 
  arrange(-count,-provs)

no_ca_words<-as.character(neg_words$word[neg_words$province=="California"])[1:2500]
no_or_words<-as.character(neg_words$word[neg_words$province=="Oregon"])[1:2500]
no_ny_words<-as.character(neg_words$word[neg_words$province=="New_York"])[1:2500]
no_ma_words<-as.character(neg_words$word[neg_words$province=="Marlborough"])[1:2500]
no_cv_words<-as.character(neg_words$word[neg_words$province=="Casablanca_Valley"])[1:2500]
no_bu_words<-as.character(neg_words$word[neg_words$province=="Burgundy"])[1:2500]

wino<-wine %>% 
  ungroup() %>% 
  mutate(
    lprice = log(price),
    #price = price,
    points = points,
    f_1=grepl(regex_ify(ca_words),description,ignore.case = T),
    f_2=grepl(regex_ify(or_words),description,ignore.case = T),
    f_3=grepl(regex_ify(ny_words),description,ignore.case = T),
    f_4=grepl(regex_ify(ma_words),description,ignore.case = T),
    f_5=grepl(regex_ify(cv_words),description,ignore.case = T),
    f_6=grepl(regex_ify(bu_words),description,ignore.case = T),
    f_1b=grepl(regex_ify(ca_words2),description,ignore.case = T),
    f_2b=grepl(regex_ify(or_words2),description,ignore.case = T),
    f_3b=grepl(regex_ify(ny_words2),description,ignore.case = T),
    f_4b=grepl(regex_ify(ma_words2),description,ignore.case = T),
    f_5b=grepl(regex_ify(cv_words2),description,ignore.case = T),
    f_6b=grepl(regex_ify(bu_words2),description,ignore.case = T),
    f_1c=grepl(regex_ify(no_ca_words),description,ignore.case = T),
    f_2c=grepl(regex_ify(no_or_words),description,ignore.case = T),
    f_3c=grepl(regex_ify(no_ny_words),description,ignore.case = T),
    f_4c=grepl(regex_ify(no_ma_words),description,ignore.case = T),
    f_5c=grepl(regex_ify(no_cv_words),description,ignore.case = T),
    f_6c=grepl(regex_ify(no_bu_words),description,ignore.case = T)
    ) %>% 
  select(province, lprice, points, f_1:f_6c)

#scale price and points 
wino = wino %>% 
  preProcess(method = c("BoxCox","center","scale")) %>% 
  predict(wino)


```


## Specification

```{r}
# specify the model to be used (i.e. KNN or Naive Bayes) and the tuning parameters used

ctrl <- trainControl(method = "cv", number = 5)
set.seed(504) 

wine_index <- createDataPartition(wino$province, p = 0.80, list = FALSE)
train <- wino[ wine_index, ]
test <- wino[-wine_index, ]

#nearest neighbor
# fit_tune <- train(province ~ .,
#              data = train, 
#              method = "knn",
#              tuneLength = 15,
#              trControl = control)
# 
# fit_tune
# 
# fit_knn <- knn(
#   train = select(train,-province), 
#   test = select(test,-province), 
#   k=11, 
#   cl = train$province, 
#   prob = T)
# 
# print(fit_knn)
# 
# pred <- predict(fit_knn, newdata=test)
# confusionMatrix(factor(pred),factor(test$province))
# 
# #tree
# fit_tree <- train(province ~ .,
#              data = train, 
#              method = "rpart",
#              trControl = ctrl,
#              metric = "Kappa")
# 
# fit_tree
# 
# confusionMatrix(predict(fit_tree, test),factor(test$province))


#random forest
# control <- trainControl(method = "boot", number = 1)
fit_rf <- train(province ~ .,
             data = train,
             method = "rf",
             trControl = ctrl)

fit_rf

pred <- predict(fit_rf, newdata=test)
confusionMatrix(factor(pred),factor(test$province))

fit=fit_rf


```


## Best model

```{r}
# Here are a few lines to inspect your best model. Add some comments about optimal hyperparameters.
print(fit)
print(fit$bestTune)
```


## Re-fit and evaluation

```{r}
# the "method" below should match the one you chose above. 

set.seed(1504) # I will choose a different seed for evaluation

wine_index <- createDataPartition(wino$province, p = 0.80, list = FALSE)
train <- wino[ wine_index, ]
test <- wino[-wine_index, ]

# example spec for knn
fit_final <- train(province ~ .,
             data = train, 
             method = "rf",
             tuneGrid=fit$bestTune) 
# The last line means we will fit a model using the best tune parameters your CV found above.

confusionMatrix(predict(fit_final, test),factor(test$province))
```

